# Generated by Django 5.2.7 on 2025-11-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={},
        ),
        migrations.RenameField(
            model_name='visit',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='referrer',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='user_agent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='visit',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
